repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: flake8
        args:
        - --exclude=*/*migrations/*
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: end-of-file-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.0.1
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
