# Generated by Django 3.2 on 2022-03-25 20:01

from django.db import migrations, models
import django.db.models.deletion


def migrate_links(apps, schema_editor):
    Group = apps.get_model('users', 'Group')
    GroupLink = apps.get_model('users', 'GroupLink')

    for group in Group.objects.all():
        if group.link1:
            GroupLink.objects.create(group=group, link=group.link1)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_group_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=2048, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='0=first, 1=second etc.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.group')),
            ],
        ),
        migrations.RunPython(migrate_links, reverse_code=lambda *_: None),
    ]
