# Generated by Django 3.2 on 2022-04-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_link1_link2_link3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token_passphrase',
        ),
        migrations.AddField(
            model_name='user',
            name='token_uuid_hashed_with_passphrase',
            field=models.CharField(blank=True, help_text='One time passphrase', max_length=128, null=True),
        ),
    ]
