version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip install -e ".[dev]"
          name: Install dependencies
      - run:
          command: pytest
          name: Run pytest
      - run:
          command: |
            sudo apt update
            sudo apt install gettext
            django-admin makemessages -l da
          name: Makemessages (build Danish translations)


workflows:
  main:
    jobs:
      - build-and-test
