# Generated by Django 3.2 on 2022-03-16 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar', '0027_add_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_hash', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('language_code', models.CharField(max_length=6)),
                ('sphere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calendar.sphere')),
            ],
        ),
        migrations.CreateModel(
            name='EventVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar.event')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.visit')),
            ],
        ),
    ]
