# Generated by Django 3.2 on 2022-03-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visitor_hash',
            field=models.CharField(max_length=64),
        ),
    ]
