# Generated by Django 3.2 on 2021-11-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0023_alter_eventrecurrence_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtime',
            name='description',
            field=models.TextField(blank=True, help_text="Leave blank to use the general event's description. If filled in, will be displayed together when a user navigates to this specific occurrence of the event.", verbose_name='description'),
        ),
    ]
