# Generated by Django 3.2 on 2022-03-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0025_subspheres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sphere',
            name='sub_spheres',
            field=models.ManyToManyField(blank=True, help_text="Other spheres intersecting or contained within this sphere. This can only have one level of 'nested' spheres - you can only choose spheres that aren't also containing other spheres.", limit_choices_to={'sub_spheres': None}, related_name='metaspheres', to='calendar.Sphere', verbose_name='Related spheres'),
        ),
    ]
