# Generated by Django 3.2 on 2022-04-20 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_token_uuid_hashed_with_passphrase'),
        ('calendar', '0027_add_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('every_week', models.BooleanField(default=False)),
                ('biweekly_even', models.BooleanField(default=False)),
                ('biweekly_odd', models.BooleanField(default=False)),
                ('first_week_of_month', models.BooleanField(default=False)),
                ('second_week_of_month', models.BooleanField(default=False)),
                ('third_week_of_month', models.BooleanField(default=False)),
                ('last_week_of_month', models.BooleanField(default=False)),
                ('opens', models.TimeField()),
                ('closes', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='users.location')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calendar.weekday')),
            ],
            options={
                'ordering': ('weekday__number', 'opens'),
            },
        ),
    ]
